name: Website Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  bucket: 's3://gucosme.dev/'
  packageName: ${{ github.head_ref }}.zip

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: 'prod'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: sa-east-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.28.0
      
      - name: install dependencies, run build
        run: |
          pnpm install
          pnpm build

      - name: zip built files and sync with s3 bucket
        run: |
          cd dist/
          zip -r ${{ env.packageName }} *
          aws s3 cp ${{ env.packageName }} ${{ env.bucket }} --acl public-read

  deploy:
    needs: build
    uses: Twilio-Demo-Engineering/workflows/.github/workflows/amplify-deploy.yaml@add-amplify-deploy
    environment: 'prod'
    with:
      package_name: ${{ github.head_ref }}
      branch_name: ${{ github.head_ref }}
      domain_name: ${{ github.head_ref }}.gucosme.dev
    secrets:
      AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: sa-east-1
